on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    create-release-pr:
        name: create release pr
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create release PR
              uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
                  release-type: simple